# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irc_notify_int <- function(irc_server, channel, message, port, ssl, server_password, nickname, username, realname) {
    invisible(.Call('irced_irc_notify_int', PACKAGE = 'irced', irc_server, channel, message, port, ssl, server_password, nickname, username, realname))
}

